services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PUBLISHEDSERVERURL=http://192.168.0.5
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ~/jellyfin/library:/config
      - ~/jellyfin/tvseries:/data/tvshows
      - ~/jellyfin/movies:/data/movies
    restart: unless-stopped

